name: CI/CD for React App

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            # 1) Checkout your code
            - name: Checkout
              uses: actions/checkout@v3

            # 2) SSH into EC2 & deploy
            - name: Deploy to EC2
              uses: appleboy/ssh-action@v0.1.6
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USERNAME }}
                  key: ${{ secrets.EC2_SSH_KEY }}
                  port: ${{ secrets.EC2_PORT }}
                  script: |
                      set -e

                      # Clone once, thereafter pull latest
                      if [ ! -d ~/react-app ]; then
                        git clone https://github.com/yogeshOzaDeanInfotech/cicd-react-demo.git ~/react-app
                      fi

                      cd ~/react-app
                      git fetch origin main
                      git reset --hard origin/main

                      # Stop & remove any existing container
                      docker stop react-app  >/dev/null 2>&1 || true
                      docker rm   react-app  >/dev/null 2>&1 || true

                      # Build new image and run it on port 80
                      docker build -t react-app:latest .
                      docker run -d \
                        --name react-app \
                        -p 80:80 \
                        --restart unless-stopped \
                        react-app:latest
